version: '3.6'

services:
  kong-database:
    image: cassandra:3.0
    volumes:
      - ./cassandra_db:/var/lib/cassandra
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  kong:
    depends_on:
      - kong-database
    image: kong:latest
    restart: always
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_NGINX_HTTP_RESOLVER: 8.8.8.8
    ports:
      - 127.0.0.1:80:8000
      - 127.0.0.1:8001:8001
